# Generated by Django 4.0.5 on 2022-07-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_enjoyment',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_purchase',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_recommend',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
