# Generated by Django 4.0.5 on 2022-07-01 04:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rating_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Featured image'),
        ),
    ]
