# Generated by Django 4.0.5 on 2022-07-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='image',
        ),
    ]
