# Generated by Django 4.0.5 on 2022-07-01 05:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_image_url_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Featured image'),
        ),
    ]
